nbuilding/N-lang

- web/package-lock.json
- web/package.json
- web/src/index.ts
I didn't bother deploying this to GitHub Pages.
You can also run the code using ctrl + enter and save the log as a text file.
> Save file on ctrl + S

- python/n.py
- python/run.n
- python/syntax.lark
Currying occurs if you pass less than the specified number of arguments. Functional programming gang!
> Fix function expressions, add currying

- README.md
- python/n.py
- python/run.n
- python/syntax.lark
I've also added support for currying and type inference, which is pretty epic
> Merge master (type-checking) into new-parse

- python/n.py
- python/run.n
Makes it nicer and fixes many problems with the error system
> New error system

- README.md
- python/n.py
`py n.py -h` helps to show the new thing with only compile-time if chosen.
> Implement a new way of command line arguments

- python/n.py
- python/run.n
- python/syntax.lark
Allows for anonymous functions to be parsed and run
> Add anonymous functions

- python/n.py
- python/run.n
- python/syntax.lark
Just added the char type, please check if there are more escape codes, those are the only ones I know.
> Add the char type

- python/n.py
- python/run.n
- python/syntax.lark
Please check for errors and things, because there are some features that need to be added.
> Add tuples

- python/n.py
- python/run.n
- python/syntax.lark
> Changes var to let and allows variables to be varied using var

- python/run.n
- python/scope.py
- python/syntax.lark
- python/type_check_error.py
Per surveys, records will use colons, newlines/semicolons, and curly brackets
> Records (Python)

- python/n.py
- python/run.n
- python/runner.n
- python/scope.py
- python/syntax.lark
- python/variable.py
Co-Authored-By: Ash Ranjan <Ashvin-Ranjan@users.noreply.github.com>
> Un-revert the actual changes

- python/function.py
- python/scope.py
type_check_command and eval_command now can handle code_blocks.
> Fix code blocks

- python/display.py
- python/run.n
- python/scope.py
The output now has epic colour and also uses N syntax
> More colourful print output

- README.md
- python/display.py
- python/enums.py
- python/native_functions.py
- python/run.n
- python/scope.py
- python/syntax.lark
- python/type.py
- python/type_check_error.py
> Enums and type aliases

- python/scope.py
- python/syntax.lark
- python/type.py
- python/type_check_error.py
```ts
let uau: { id: str } = { id: "uauauau" }
```
now works
> Parse record defs and fix applying generics to records and displaying ()

- python/cmd.py
- python/function.py
- python/n.py
- python/native_function.py
- python/native_functions.py
- python/run.n
- python/scope.py
- python/syntax.lark
- python/type.py
You can use it in any function that returns a `cmd`
> Await operator

- python/discord.n
- python/libraries/request.py
- python/native_functions.py
- python/parser.py
- python/run.n
- python/scope.py
- python/syntax.lark
So it adds await which is pretty cool
> Merge from main

- python/function.py
- python/libraries/json.py
- python/native_function.py
- python/run.n
- python/runner.n
- python/scope.py
- python/syntax.lark
- python/type.py
- python/type_check_error.py
Power went down so couldn't push
> JSON parser and exporting lists

- README.md
- python/libraries/websocket.py
- python/run.n
- python/scope.py
- python/variable.py
Here's an overview of the type signatures of its exports:
```ts
alias pub send = str -> cmd[()]
alias connectOptions = {
onOpen: (str -> cmd[()]) -> cmd[()]
onMessage: (str -> cmd[()]) -> str -> cmd[()]
onClose: cmd[()]
}
let pub connect: connectOptions -> str -> cmd[()]
```
Here's an example
```ts
import websocket
// https://www.websocket.org/echo.html
let pub websocketTest = <websocket.connect {
onOpen: [send: websocket.send] -> cmd[bool] {
print "Open!"
let _ = <send "hi">!
return false
}
onMessage: [send: websocket.send message: str] -> cmd[bool] {
print message
let _ = <send "hello">!
return message == "hello"
}
} "wss://echo.websocket.org">
```
You pass in two functions, `onOpen` and `onMessage`, in a record:
- `onOpen` takes a `websocket.send`, which is an alias for a function that …
> Websockets

- python/discord.n
- python/n.py
> Remove dumb hacks and change `asyncio.run` to `asyncio.get_event_loop().run_until_complete`

- python/discord.n
- python/scope.py
I didn't fix
```
Error: You haven't yet defined userdata.
--> discord.n:113:21
113 |             sender: userdata
^^^^^^^^
```
because I also don't know what `userdata` refers to.
> Fix most of the errors

- python/file.py
- python/libraries/FileIO.py
- python/libraries/websocket.py
- python/n.py
- python/scope.py
And websockets now return a maybe[str] in case Discord gets pissed and closes the websocket
> Better support for file paths, and FileIO.read now returns a maybe in case the file doesn't exist

- python/file.py
- python/libraries/FileIO.py
- python/libraries/request.py
- python/libraries/websocket.py
- python/n.py
- python/scope.py
I am generally confused because I am in class
> merge main into class

- .gitattributes
Per https://github.com/github/linguist#overrides
> Reclassify .n as N

- install.ps1
Untested
In PowerShell,
```ps
iwr https://github.com/nbuilding/N-lang/raw/installer/install.ps1 -useb | iex
```
to install N
> Create installer script (PowerShell) based on Deno

- examples/fizzbuzz.n
- python/n.py
- python/run.n
- python/scope.py
- python/syntax.lark
```ts
let wow = imp "../ok.n"
```
Relative paths only rn
> Import by relative file path

- python/libraries/websocket.py
```sh
N_WS_DEBUG=experimental python n.py
```
> Websocket debugging with N_WS_DEBUG=experimental

- python/native_functions.py
- python/operation_types.py
- python/run.n
- python/scope.py
- python/syntax.lark
Change for loop syntax from
```
for i 10 {
print(i)
}
```
to
```
for value in iterable {
print(value)
}
```
After this is finished `v1.2.0` will be released
> Change syntax for for loop

- python/n.py
- python/run.n
- python/scope.py
Fix the error described in Issue #75
> Fix bug with if/else and conditional lets

- python/run.n
- python/syntax.lark
> Fix issue #81

- python/run.n
- python/scope.py
> Fix bug in issue #79

- python/n.py
- python/run.n
- python/scope.py
- python/syntax.lark
- python/syntax_error.py
> Fancy unexpected EOF error message

- python/classes.py
- python/run.n
- python/scope.py
- python/type.py
- python/type_check_error.py
> This should fix #92

- tests/syntax/function-calls.n
This can close #82 as a rejected non-issue
> Revise function calls test based on discussion

- .github/workflows/release.yml
Created a Github Actions workflow, `release.yml`, which automatically builds, zips, and creates a draft release on creation of every new tag.
> create release workflow

- python/classes.py
- python/display.py
- python/enums.py
- python/file.py
- python/function.py
- python/imported_error.py
- python/libraries/FileIO.py
- python/libraries/SystemIO.py
- python/libraries/fek.py
- python/libraries/json.py
- python/libraries/request.py
- python/libraries/times.py
- python/libraries/websocket.py
- python/modules.py
- python/n.py
- python/native_function.py
- python/native_functions.py
- python/native_types.py
- python/ncmd.py
- python/operation_types.py
- python/parse.py
- python/parse_test.py
- python/scope.py
- python/syntax_error.py
- python/type.py
- python/type_check_error.py
- python/variable.py
I formatted everything using pycharm's nice formatter.
> Use pycharm pep8 formatter

- docs/features/enums.md
- docs/features/generic.md
> enum and typevar guide

- PROJECTS.md
This is a PR to add more projects into `PROJECTS.md` without flooding `main` with meaningless commits, once you added your project(s) to `PROJECTS.md` on your own branch make a PR into this branch and when we get 25 I will merge this into `main`
Projects:
> If you want to add your project look here first.

- python/imported_error.py
- python/n.py
- python/run.n
- python/runner.n
> Closes #114

- python/libraries/times.py
- python/run.n
> Closes #130

- python/operation_types.py
- python/run.n
- python/scope.py
Closes #127 
Allows for the negative sign to be attached to a variable, even multiple times.
> Closes #127

- python/n.py
- python/run.n
- python/scope.py
> Closes #126

- docs/features/aliases.md
- docs/features/destructuring.md
- docs/features/internal_libraries.md
Fixes incorrect syntax and duplicate variables.
> Fix errors in docs

- python/run.n
- python/scope.py
- python/syntax.lark
> Fixes #124

- python/parse.py
- python/scope.py
- python/syntax.lark
- python/syntax_error.py
Make a hotfix for the major bug in `v1.2.2`
> Hotfix v1.2.2

- python/native_functions.py
- python/operation_types.py
- python/run.n
> Fix #142 and #141

- python/libraries/json.py
- python/run.n
> Closes #143

- python/n.py
- python/native_functions.py
- python/run.n
Closes #128 and adds `--newest`
> Add some features

- python/scope.py
- python/syntax.lark
- tests/features/while.n
> Add While Loops and other features

- python/scope.py
- python/syntax.lark
- tests/features/while.n
> Add while and accompanying features

- python/n.py
> Add --version and --update

- python/run.n
- python/scope.py
- python/type_check_error.py
closes #169 
closes #170 (hopefully)
> Fix several bugs that have come up

- python/run.n
- python/scope.py
> Close #155 using very weird code

- python/function.py
- python/run.n
- python/scope.py
- python/type_check_error.py
> Fix what was going on with no argument functions

- python/run.n
- python/runner.n
- python/scope.py
> Fixes circular imports

- python/native_functions.py
- python/run.n
> Add some features that were missing

- python/n.py
Updates the descriptions on all flags for N.
> Update flag descriptions.

- python/run.n
- python/scope.py
- python/syntax.lark
Adds hex, binary, and octal literals.
> Add new literals

- tests/assertions/basics.n
- tests/assertions/tuples-lists-records.n
- tests/syntax/literals.n
and the like
Please make sure the new tests are correct
> Add a few more tests for floats and strings

- examples/test.n
- python/native_functions.py
> Add parallel : [a] cmd[a] -> cmd[cmd[a]]

- python/operation_types.py
- tests/assertions/basics.n
- tests/assertions/imports/import.n
- tests/assertions/imports/unit-test.n
- tests/assertions/internal-libraries.n
- tests/assertions/match.n
- tests/assertions/native-functions.n
- tests/assertions/tuples-lists-records.n
- tests/assertions/while.n
- tests/syntax/order-of-operations.n
Please check if the tests make sense
> Add more tests for new features in N 1.3

- python/run.n
- python/scope.py
Sadly we cannot stop repeated values, that will just be whichever one is the last one will be run.
> Stop double defaults in `match`

- PROJECTS.md
- python/libraries/websocket.py
- python/n.py
- python/native_functions.py
- python/ncmd.py
- python/run.n
- python/scope.py
- python/syntax.lark
- python/type.py
- tests/assertions/native-functions.n
closes #219 
closes #220 
closes #221 
closes #224 
closes #227 
closes #228 
closes #230 
closes #231 
closes #233
> Close bugs for `v1.3.1`

- tests/assertions/basics.n
- tests/assertions/native-functions.n
Defines previously undefined behaviour:
- Fixes #243
- Fixes #245
- Fixes #246
> Add bugs to tests to make sure they don't happen again

- tests/assertions/internal-libraries.n
- tests/assertions/js.n
- tests/assertions/mutex.n
- tests/assertions/native-functions.n
- tests/assertions/python.n
- tests/assertions/tuples-lists-records.n
- tests/assertions/typescript-features.n
- tests/syntax/function-calls.n
These should fix the linked issues because adding to the tests adds them to the languages. Implementations would then have to be fixed to become compliant with the tests
> Implement some new features for N Next

- tests/syntax/function-expressions-and-better-patterns.n
Addresses #259 and #270
I haven't updated the other tests because presumably further discussion is still needed
> Proposal for new function expression and better pattern syntax
